Updated Workflow Files

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,71 +1,119 @@
-# YAML file for GitHub Actions workflow
+# # YAML file for GitHub Actions workflow
 
-name: Packer Format and Validate
+# name: Packer Format and Validate
+
+# on:
+#   pull_request:
+#     branches:
+#       - main
+#   workflow_dispatch:
+  
+
+# jobs:
+#   format_and_validate:
+#     runs-on: ubuntu-latest
+#     env:
+#       AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
+#       SOURCE_AMI: ${{ secrets.SOURCE_AMI }}
+#       SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
+#       DEFAULT_SUBNET_ID: ${{ secrets.DEFAULT_SUBNET_ID }}
+#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#       # AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
+#       AWS_AMI_USERS: ${{ secrets.AWS_AMI_USERS }}
+
+#     strategy:
+#       matrix:
+#         node-version: [16.x]  # Adjust the Node.js version as needed
+
+#     steps:
+#       - name: Checkout Code
+#         uses: actions/checkout@v2
+
+#       - name: Setup Node.js
+#         uses: actions/setup-node@v2
+#         with:
+#           node-version: ${{ matrix.node-version }}
+#           cache: 'npm'
+
+#       - name: Install Dependencies
+#         run: npm ci
+
+    
+
+
+
+#       - name: Initialize Packer
+#         run: packer init aws_ami.pkr.hcl
+
+#       - name: Check Packer Configuration Format
+#         run: |
+#           packer fmt -check aws_ami.pkr.hcl
+#           if [ $? -ne 0 ]; then
+#             echo "Packer template format check failed. Please fix the formatting."
+#             exit 1
+#           fi
+
+#       - name: Validate Packer Configuration
+#         run: |
+#           packer validate aws_ami.pkr.hcl
+#           if [ $? -ne 0 ]; then
+#             echo "Packer template validation failed. Please fix the template."
+#             exit 1
+#           fi
+
+
+
+name: Node.js CI [Unit tests]
+
+ 
 
 on:
   pull_request:
-    branches:
-      - main
-  workflow_dispatch:
-  
+    branches: [ main ]
+
+ 
 
 jobs:
-  format_and_validate:
+  tests:
     runs-on: ubuntu-latest
     env:
-      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
       SOURCE_AMI: ${{ secrets.SOURCE_AMI }}
       SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
       DEFAULT_SUBNET_ID: ${{ secrets.DEFAULT_SUBNET_ID }}
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-      # AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
+      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
       AWS_AMI_USERS: ${{ secrets.AWS_AMI_USERS }}
-
     strategy:
       matrix:
-        node-version: [16.x]  # Adjust the Node.js version as needed
-
+        node-version: [16.x]
     steps:
-      - name: Checkout Code
-        uses: actions/checkout@v2
+    - uses: actions/checkout@v2
+    - run: npm i    
+    - name: Use Node.js ${{ matrix.node-version }}
+      uses: actions/setup-node@v2
+      with:
+        node-version: ${{ matrix.node-version }}
+        cache: 'npm'
+    - run: npm run build --if-present
+    - run: npm test
+    - run: zip -r webapp.zip *
+    - run: unzip -l webapp.zip
+    - name: Initialize Packer
+      run: packer init packer/test.pkr.hcl
 
-      - name: Setup Node.js
-        uses: actions/setup-node@v2
-        with:
-          node-version: ${{ matrix.node-version }}
-          cache: 'npm'
-
-      - name: Install Dependencies
-        run: npm ci
-
-      - name: Build (if present)
-        run: npm run build --if-present
-
-      - name: Run Tests
-        run: npm test -- --exit
-
-      # - name: Create Zip Archive
-      #   run: zip -r webapp.zip *.js *.json
-
-      # - name: List Zip Archive Contents
-      #   run: unzip -l webapp.zip
-
-      - name: Initialize Packer
-        run: packer init aws_ami.pkr.hcl
-
-      - name: Check Packer Configuration Format
-        run: |
-          packer fmt -check aws_ami.pkr.hcl
-          if [ $? -ne 0 ]; then
-            echo "Packer template format check failed. Please fix the formatting."
-            exit 1
-          fi
-
-      - name: Validate Packer Configuration
-        run: |
-          packer validate aws_ami.pkr.hcl
-          if [ $? -ne 0 ]; then
-            echo "Packer template validation failed. Please fix the template."
-            exit 1
-          fi
+    - name: Check Packer Configuration Format
+      run: |
+        packer fmt  packer/test.pkr.hcl
+        if [ $? -ne 0 ]; then
+          echo "Packer template format check failed. Please fix the formatting."
+          exit 1
+        fi
+    - name: Validate Packer Configuration
+      run: |
+        packer validate packer/test.pkr.hcl
+        if [ $? -ne 0 ]; then
+          echo "Packer template validation failed. Please fix the template."
+          exit 1
+        fi
